name: Publish Docker image on tag
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Determine Short SHA
        run: echo "SHORT_SHA=${{ github.sha }}" >> $GITHUB_ENV
      - 
        name: Determine release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Sanitize Repo Name for Tagging
        run: echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]' | (read; echo REPO_LOWER=$REPLY) >> $GITHUB_ENV
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.CLOUDY_USERNAME }}
          password: ${{ secrets.CLOUDY_TOKEN }}
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}:latest
            ghcr.io/${{ env.REPO_LOWER }}:${{ env.SHORT_SHA }}
            ghcr.io/${{ env.REPO_LOWER }}:${{ env.RELEASE_VERSION }}
      - 
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

